method: TOTAL3D
resume: False
finetune: True
weight: ['out/pretrained_models/total3d/model_best.pth',
         'out/layout_estimation/20101621195486/model_best.pth',
         'out/ldif/20101613380518/model_best.pth']
seed: 123
device:
  use_gpu: True
  gpu_ids: '0'
  num_workers: 4
data:
  dataset: sunrgbd
  split: data/sunrgbd/splits
  bounding_box: 0.7
  coarse_grid_spacing: 0.04375
  marching_cube_resolution: 128
loss_weights:
  size_reg_loss: 1.0
  ori_cls_loss: 0.33
  ori_reg_loss: 1.0
  centroid_cls_loss: 0.75
  centroid_reg_loss: 0.5
  offset_2D_loss: 0.5
  pitch_cls_loss: 0.25
  pitch_reg_loss: 1.0
  roll_cls_loss: 0.25
  roll_reg_loss: 0.5
  lo_ori_cls_loss: 0.25
  lo_ori_reg_loss: 0.75
  lo_centroid_loss: 1.0
  lo_coeffs_loss: 1.0
  lo_corner_loss: 1.0
  phy_loss: 0.75
  bdb2D_loss: 0.75
  corner_loss: 0.75
  ldif_phy_loss: 0.0
model:
  layout_estimation:
    method: PoseNet
    loss: PoseLoss
  object_detection:
    method: Bdb3DNet
    loss: DetLoss
  mesh_reconstruction:
    method: LDIF
    loss: LDIFReconLoss
    bottleneck_size: 1536
    element_count: 32
    sym_element_count: 16
    implicit_parameter_length: 32
    object_samples: 512
    loss_settings:
      scale_before_func: 100.0
      type: classmse
  output_adjust:
    method: GCNN
    loss: Null
    feature_dim: 512
    feat_update_step: 4
    res_output: True
    lo_features: ['pitch_reg_result', 'roll_reg_result', 'pitch_cls_result',
                  'roll_cls_result', 'lo_ori_reg_result', 'lo_ori_cls_result',
                  'lo_centroid_result', 'lo_coeffs_result', 'lo_afeatures', 'K']
    obj_features: ['size_cls', 'cls_codes', 'size_reg_result', 'ori_reg_result', 'ori_cls_result',
                   'centroid_reg_result', 'centroid_cls_result', 'offset_2D_result',
                   'analytic_code', 'odn_arfeatures', 'blob_center']
    rel_features: ['g_features', 'bdb2D_pos']
optimizer:
  method: Adam
  lr: 1e-4
  betas: [0.9, 0.999]
  eps: 1e-08
  weight_decay: 1e-04
scheduler:
  method: MultiStepLR
  milestones: [18, 23, 28]
  gamma: 0.5
train:
  epochs: 30
  phase: 'joint' # 'layout_estimation' or 'object_detection' or 'joint'.
  freeze: ['layout_estimation', 'object_detection', 'mesh_reconstruction']
  batch_size: 2
val:
  phase: 'joint'
  batch_size: 2
test:
  phase: 'joint'
  batch_size: 1
demo:
  phase: 'joint'
log:
  vis_path: visualization
  save_results: True
  vis_step: 100
  print_step: 50
  path: out/total3d




